import { useEffect, useState } from "react";
import { DashboardLayout } from "@/components/DashboardLayout";
import { AddExpenseDialog } from "@/components/AddExpenseDialog";
import { AIExpenseImportDialog } from "@/components/AIExpenseImportDialog";
import { DateFilter } from "@/components/DateFilter";
import { useFinance } from "@/context/FinanceContext";
import { formatCurrency, formatDate, expenseCategories, getTodayBR } from "@/lib/finance-data";
import { useLibertyData } from "@/hooks/useLibertyData";
import { useAdsSpend } from "@/hooks/useAdsSpend";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { CreditCard } from "lucide-react";
import {
  PieChart, Pie, Cell, ResponsiveContainer, Tooltip, Legend,
} from "recharts";

const PIE_COLORS = [
  "hsl(152, 60%, 48%)", "hsl(210, 80%, 55%)", "hsl(40, 90%, 58%)",
  "hsl(280, 60%, 55%)", "hsl(0, 72%, 55%)", "hsl(180, 60%, 45%)",
  "hsl(30, 70%, 50%)", "hsl(320, 60%, 50%)", "hsl(60, 70%, 50%)", "hsl(100, 50%, 45%)",
];

const PAYMENT_SOURCE_LABELS: Record<string, string> = {
  caixa: "Caixa",
  saque: "Saque",
  nao_paga: "Não Paga",
};

const Expenses = () => {
  const { expenses, selectedDate, dateRange, addAutoExpenses, registerFbAdsPayment, fbAdsAccumulated, fbAdsPaid } = useFinance();
  const { data: libertyData } = useLibertyData(dateRange.from, dateRange.to);
  const { data: adsData } = useAdsSpend(dateRange.from, dateRange.to);

  // Auto-inject frete + ads as expenses
  useEffect(() => {
    const autoExpenses: any[] = [];
    const today = getTodayBR();

    // Auto Frete
    const totalFrete = libertyData?.summary?.totalFrete ?? 0;
    if (totalFrete > 0) {
      autoExpenses.push({
        date: today,
        description: "Frete (automático - LibertyPainel)",
        category: "Logística",
        amount: totalFrete,
        type: "variavel",
        status: "pago",
        isAutoGenerated: true,
      });
    }

    // Auto Facebook ADS - enters as "agendado" (fatura pendente)
    const adsSpend = adsData?.totalSpend ?? 0;
    if (adsSpend > 0) {
      const adsWithTax = adsSpend * 1.12;
      const remaining = Math.max(0, adsWithTax - fbAdsPaid);
      if (remaining > 0) {
        autoExpenses.push({
          date: today,
          description: `FATURA FACEBOOK ADS (${formatCurrency(adsWithTax)} total - ${formatCurrency(fbAdsPaid)} pago)`,
          category: "Facebook ADS",
          amount: remaining,
          type: "variavel",
          status: "agendado",
          isAutoGenerated: true,
        });
      }
    }

    addAutoExpenses(autoExpenses);
  }, [libertyData, adsData, fbAdsPaid]);

  const totalMonth = expenses.reduce((s, e) => s + e.amount, 0);
  const totalDay = expenses.filter(e => e.date === selectedDate).reduce((s, e) => s + e.amount, 0);

  // By category
  const byCategory = [...expenseCategories, "Facebook ADS", "Logística"].map(cat => ({
    name: cat,
    value: expenses.filter(e => e.category === cat).reduce((s, e) => s + e.amount, 0),
  })).filter(c => c.value > 0);

  // Unique categories
  const uniqueCategories = Array.from(new Set(byCategory.map(c => c.name)));

  // FB Ads fatura info
  const adsSpendTotal = (adsData?.totalSpend ?? 0) * 1.12;
  const faturaRestante = Math.max(0, adsSpendTotal - fbAdsPaid);

  return (
    <DashboardLayout title="Custos & Despesas" subtitle="Controle detalhado de gastos">
      <div className="flex items-center justify-between mb-6">
        <DateFilter />
        <div className="flex gap-2">
          <AIExpenseImportDialog />
          <AddExpenseDialog />
        </div>
      </div>

      {/* Summary */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mb-6">
        <div className="glass-card p-5">
          <p className="text-[10px] text-muted-foreground uppercase tracking-wider mb-1">Total do Mês</p>
          <p className="text-xl font-bold font-mono text-foreground">{formatCurrency(totalMonth)}</p>
        </div>
        <div className="glass-card p-5">
          <p className="text-[10px] text-muted-foreground uppercase tracking-wider mb-1">Total do Dia ({formatDate(selectedDate)})</p>
          <p className="text-xl font-bold font-mono text-foreground">{formatCurrency(totalDay)}</p>
        </div>
        <div className="glass-card p-5">
          <p className="text-[10px] text-muted-foreground uppercase tracking-wider mb-1">Média Diária</p>
          <p className="text-xl font-bold font-mono text-foreground">{formatCurrency(totalMonth / 28)}</p>
        </div>
      </div>

      {/* FB Ads Fatura Card */}
      {adsSpendTotal > 0 && (
        <div className="glass-card p-5 mb-6 border-l-4 border-primary">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-sm font-semibold text-foreground flex items-center gap-2">
                <CreditCard className="w-4 h-4" />
                Fatura Facebook ADS
              </h3>
              <p className="text-[10px] text-muted-foreground mt-1">
                Total gasto + 12% imposto: <strong className="text-foreground">{formatCurrency(adsSpendTotal)}</strong> · 
                Já pago: <strong className="text-chart-positive">{formatCurrency(fbAdsPaid)}</strong> · 
                Restante: <strong className="text-chart-negative">{formatCurrency(faturaRestante)}</strong>
              </p>
              <p className="text-[10px] text-muted-foreground mt-0.5 italic">
                Quando o Facebook debitar do cartão, registre o pagamento abaixo.
              </p>
            </div>
            <FbAdsPaymentDialog onPay={registerFbAdsPayment} remaining={faturaRestante} />
          </div>
          {/* Progress bar */}
          <div className="mt-3 h-2 rounded-full bg-muted overflow-hidden">
            <div 
              className="h-full rounded-full bg-primary transition-all" 
              style={{ width: `${adsSpendTotal > 0 ? Math.min(100, (fbAdsPaid / adsSpendTotal) * 100) : 0}%` }} 
            />
          </div>
          <p className="text-[9px] text-muted-foreground mt-1 text-right">
            {adsSpendTotal > 0 ? Math.round((fbAdsPaid / adsSpendTotal) * 100) : 0}% quitado
          </p>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 mb-6">
        {/* Pie Chart */}
        <div className="glass-card p-6">
          <h3 className="text-sm font-semibold text-foreground mb-4">Despesas por Categoria</h3>
          <ResponsiveContainer width="100%" height={280}>
            <PieChart>
              <Pie data={byCategory} cx="50%" cy="50%" innerRadius={55} outerRadius={90} paddingAngle={3} dataKey="value">
                {byCategory.map((_, i) => <Cell key={i} fill={PIE_COLORS[i % PIE_COLORS.length]} />)}
              </Pie>
              <Tooltip contentStyle={{ backgroundColor: "hsl(222, 20%, 11%)", border: "1px solid hsl(222, 15%, 18%)", borderRadius: "8px", fontSize: "11px" }}
                formatter={(value: number) => [formatCurrency(value), ""]} />
              <Legend wrapperStyle={{ fontSize: "10px" }} />
            </PieChart>
          </ResponsiveContainer>
        </div>

        {/* Full Table */}
        <div className="lg:col-span-2 glass-card p-6">
          <h3 className="text-sm font-semibold text-foreground mb-4">Todos os Lançamentos</h3>
          <div className="overflow-x-auto max-h-[400px] overflow-y-auto">
            <table className="w-full text-xs">
              <thead className="sticky top-0 bg-card">
                <tr className="border-b border-border text-muted-foreground">
                  <th className="text-left pb-3 font-medium">Data</th>
                  <th className="text-left pb-3 font-medium">Descrição</th>
                  <th className="text-left pb-3 font-medium">Categoria</th>
                  <th className="text-left pb-3 font-medium">Tipo</th>
                  <th className="text-left pb-3 font-medium">Fonte</th>
                  <th className="text-right pb-3 font-medium">Valor</th>
                  <th className="text-center pb-3 font-medium">Status</th>
                </tr>
              </thead>
              <tbody>
                {expenses.map(e => (
                  <tr key={e.id} className={`border-b border-border/50 hover:bg-muted/30 transition-colors ${e.isAutoGenerated ? "bg-muted/10" : ""}`}>
                    <td className="py-2.5 font-mono text-muted-foreground">{formatDate(e.date)}</td>
                    <td className="py-2.5 font-medium text-foreground">
                      {e.description}
                      {e.isAutoGenerated && (
                        <span className="ml-1.5 text-[9px] text-primary font-semibold">AUTO</span>
                      )}
                    </td>
                    <td className="py-2.5">
                      <span className="px-2 py-0.5 rounded-md bg-muted text-muted-foreground text-[10px] uppercase tracking-wider">{e.category}</span>
                    </td>
                    <td className="py-2.5 text-[10px] text-muted-foreground capitalize">{e.type}</td>
                    <td className="py-2.5 text-[10px] text-muted-foreground">
                      {e.paymentSource ? PAYMENT_SOURCE_LABELS[e.paymentSource] : "—"}
                    </td>
                    <td className="py-2.5 text-right font-mono font-bold text-chart-negative">{formatCurrency(e.amount)}</td>
                    <td className="py-2.5 text-center">
                      <Badge variant={e.status === "pago" ? "default" : e.status === "agendado" ? "outline" : "secondary"} className="text-[9px]">{e.status}</Badge>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </DashboardLayout>
  );
};

// Sub-component: dialog to register FB Ads payment
function FbAdsPaymentDialog({ onPay, remaining }: { onPay: (amount: number, source: "caixa" | "saque" | "nao_paga") => void; remaining: number }) {
  const [open, setOpen] = useState(false);
  const [amount, setAmount] = useState("");
  const [source, setSource] = useState<"caixa" | "saque">("caixa");

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const val = parseFloat(amount);
    if (!val || val <= 0) return;
    onPay(val, source);
    setOpen(false);
    setAmount("");
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button size="sm" variant="outline" className="gap-1.5" disabled={remaining <= 0}>
          <CreditCard className="w-3.5 h-3.5" />
          Registrar Pagamento
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-sm">
        <DialogHeader>
          <DialogTitle>Pagamento Facebook ADS</DialogTitle>
        </DialogHeader>
        <p className="text-xs text-muted-foreground mb-2">
          Restante da fatura: <strong className="text-foreground">{formatCurrency(remaining)}</strong>
        </p>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2">
            <Label>Valor Pago (R$)</Label>
            <Input type="number" min="0" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} placeholder="0,00" />
          </div>
          <div className="space-y-2">
            <Label>Saiu de onde?</Label>
            <Select value={source} onValueChange={v => setSource(v as any)}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="caixa">Conta Bancária (Caixa)</SelectItem>
                <SelectItem value="saque">Saque Pendente</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <Button type="submit" className="w-full">Confirmar Pagamento</Button>
        </form>
      </DialogContent>
    </Dialog>
  );
}

export default Expenses;