import React, { createContext, useContext, useState, useMemo, useCallback, useEffect, ReactNode } from "react";
import { 
  Expense, expenses as initialExpenses, 
  expenseCategories, getTodayBR, PaymentSource
} from "@/lib/finance-data";
import { supabase } from "@/integrations/supabase/client";
import { fetchFinanceManualValues, saveFinanceManualValue, type FinanceManualValueKey } from "@/lib/finance-manual-values";
import { useAuth } from "@/context/AuthContext";

export type CountryFilter = "todos" | "brasil" | "uruguay";

interface FinanceContextType {
  expenses: Expense[];
  allExpenses: Expense[];
  addExpense: (expense: Omit<Expense, "id">) => Promise<{ success: boolean; error?: string }>;
  updateExpense: (id: string, data: Partial<Omit<Expense, "id">>) => Promise<{ success: boolean; error?: string }>;
  deleteExpense: (id: string) => Promise<{ success: boolean; error?: string }>;
  addAutoExpenses: (autoExpenses: Omit<Expense, "id">[]) => void;
  registerFbAdsPayment: (amount: number, source: PaymentSource) => Promise<{ success: boolean; error?: string }>;
  fbAdsAccumulated: number;
  fbAdsPaid: number;
  selectedDate: string;
  setSelectedDate: (date: string) => void;
  dateRange: { from: string; to: string };
  setDateRange: (range: { from: string; to: string }) => void;
  countryFilter: CountryFilter;
  setCountryFilter: (country: CountryFilter) => void;
  manualCash: number | null;
  setManualCash: (value: number | null) => void;
  manualCashBR: number | null;
  setManualCashBR: (value: number | null) => void;
  manualCashUY: number | null;
  setManualCashUY: (value: number | null) => void;
  manualSaqueBR: number | null;
  setManualSaqueBR: (value: number | null) => void;
  manualSaqueUY: number | null;
  setManualSaqueUY: (value: number | null) => void;
}

const FinanceContext = createContext<FinanceContextType | undefined>(undefined);

const today = getTodayBR();

function readStoredNumber(key: string): number | null {
  if (typeof window === "undefined") return null;
  const stored = localStorage.getItem(key);
  if (stored === null || stored.trim() === "") return null;
  const parsed = Number(stored);
  return Number.isFinite(parsed) ? parsed : null;
}

function syncStoredNumber(key: string, value: number | null) {
  if (typeof window === "undefined") return;
  if (value === null) {
    localStorage.removeItem(key);
    return;
  }

  localStorage.setItem(key, String(value));
}

function rowToExpense(row: any): Expense {
  return {
    id: row.id,
    date: row.date,
    description: row.description,
    category: row.category,
    amount: Number(row.amount),
    type: row.type as Expense["type"],
    status: row.status as Expense["status"],
    country: row.country as Expense["country"],
    paymentSource: row.payment_source as PaymentSource | undefined,
    isAutoGenerated: row.is_auto_generated,
  };
}

export function FinanceProvider({ children }: { children: ReactNode }) {
  const [allExpenses, setAllExpenses] = useState<Expense[]>(initialExpenses);
  const [selectedDate, setSelectedDate] = useState(today);
  const [dateRange, setDateRange] = useState({ from: today, to: today });
  const [countryFilter, setCountryFilter] = useState<CountryFilter>("todos");
  const [fbAdsPaid, setFbAdsPaidState] = useState<number>(() => readStoredNumber("fbAdsPaid") ?? 0);
  const [manualCash, setManualCashState] = useState<number | null>(() => readStoredNumber("manualCash"));
  const [manualCashBR, setManualCashBRState] = useState<number | null>(() => readStoredNumber("manualCashBR"));
  const [manualCashUY, setManualCashUYState] = useState<number | null>(() => readStoredNumber("manualCashUY"));
  const [manualSaqueBR, setManualSaqueBRState] = useState<number | null>(() => readStoredNumber("manualSaqueBR"));
  const [manualSaqueUY, setManualSaqueUYState] = useState<number | null>(() => readStoredNumber("manualSaqueUY"));

  useEffect(() => {
    const loadExpenses = async () => {
      const { data, error } = await supabase
        .from("expenses")
        .select("*")
        .order("created_at", { ascending: false });
      if (!error && data && data.length > 0) {
        setAllExpenses(data.map(rowToExpense));
      }
    };
    loadExpenses();
  }, []);

  useEffect(() => {
    let isMounted = true;

    const loadManualValues = async () => {
      const localValues = {
        manualCash: readStoredNumber("manualCash"),
        manualCashBR: readStoredNumber("manualCashBR"),
        manualCashUY: readStoredNumber("manualCashUY"),
        manualSaqueBR: readStoredNumber("manualSaqueBR"),
        manualSaqueUY: readStoredNumber("manualSaqueUY"),
        fbAdsPaid: readStoredNumber("fbAdsPaid") ?? 0,
      };

      try {
        const remoteValues = await fetchFinanceManualValues();
        if (!isMounted) return;

        const resolvedManualCash = remoteValues.manualCash ?? localValues.manualCash;
        const resolvedManualCashBR = remoteValues.manualCashBR ?? localValues.manualCashBR;
        const resolvedManualCashUY = remoteValues.manualCashUY ?? localValues.manualCashUY;
        const resolvedManualSaqueBR = remoteValues.manualSaqueBR ?? localValues.manualSaqueBR;
        const resolvedManualSaqueUY = remoteValues.manualSaqueUY ?? localValues.manualSaqueUY;
        const resolvedFbAdsPaid = remoteValues.fbAdsPaid ?? localValues.fbAdsPaid;

        setManualCashState(resolvedManualCash ?? null);
        setManualCashBRState(resolvedManualCashBR ?? null);
        setManualCashUYState(resolvedManualCashUY ?? null);
        setManualSaqueBRState(resolvedManualSaqueBR ?? null);
        setManualSaqueUYState(resolvedManualSaqueUY ?? null);
        setFbAdsPaidState(resolvedFbAdsPaid ?? 0);

        syncStoredNumber("manualCash", resolvedManualCash ?? null);
        syncStoredNumber("manualCashBR", resolvedManualCashBR ?? null);
        syncStoredNumber("manualCashUY", resolvedManualCashUY ?? null);
        syncStoredNumber("manualSaqueBR", resolvedManualSaqueBR ?? null);
        syncStoredNumber("manualSaqueUY", resolvedManualSaqueUY ?? null);
        syncStoredNumber("fbAdsPaid", resolvedFbAdsPaid ?? 0);

        const migrationTasks: Promise<unknown>[] = [];

        if (remoteValues.manualCash === undefined && localValues.manualCash !== null) {
          migrationTasks.push(saveFinanceManualValue("manualCash", localValues.manualCash));
        }
        if (remoteValues.manualSaqueBR === undefined && localValues.manualSaqueBR !== null) {
          migrationTasks.push(saveFinanceManualValue("manualSaqueBR", localValues.manualSaqueBR));
        }
        if (remoteValues.manualSaqueUY === undefined && localValues.manualSaqueUY !== null) {
          migrationTasks.push(saveFinanceManualValue("manualSaqueUY", localValues.manualSaqueUY));
        }
        if (remoteValues.manualCashBR === undefined && localValues.manualCashBR !== null) {
          migrationTasks.push(saveFinanceManualValue("manualCashBR", localValues.manualCashBR));
        }
        if (remoteValues.manualCashUY === undefined && localValues.manualCashUY !== null) {
          migrationTasks.push(saveFinanceManualValue("manualCashUY", localValues.manualCashUY));
        }
        if (remoteValues.fbAdsPaid === undefined && localValues.fbAdsPaid > 0) {
          migrationTasks.push(saveFinanceManualValue("fbAdsPaid", localValues.fbAdsPaid));
        }

        if (migrationTasks.length > 0) {
          await Promise.all(migrationTasks);
        }
      } catch (error) {
        console.error("Erro ao carregar valores manuais", error);
      }
    };

    loadManualValues();

    return () => {
      isMounted = false;
    };
  }, []);

  const persistManualValue = useCallback((key: FinanceManualValueKey, value: number | null) => {
    syncStoredNumber(key, value);
    void saveFinanceManualValue(key, value).catch((error) => {
      console.error(`Erro ao salvar ${key}`, error);
    });
  }, []);

  const setManualCash = (value: number | null) => {
    setManualCashState(value);
    persistManualValue("manualCash", value);
  };
  const setManualCashBR = (value: number | null) => {
    setManualCashBRState(value);
    persistManualValue("manualCashBR", value);
  };
  const setManualCashUY = (value: number | null) => {
    setManualCashUYState(value);
    persistManualValue("manualCashUY", value);
  };
  const setManualSaqueBR = (value: number | null) => {
    setManualSaqueBRState(value);
    persistManualValue("manualSaqueBR", value);
  };
  const setManualSaqueUY = (value: number | null) => {
    setManualSaqueUYState(value);
    persistManualValue("manualSaqueUY", value);
  };

  const expenses = useMemo(() => {
    if (countryFilter === "todos") return allExpenses;
    // Include expenses that match the country OR have no country (shared) OR country is "ambos"
    return allExpenses.filter(e => !e.country || e.country === countryFilter || (e as any).country === "ambos");
  }, [allExpenses, countryFilter]);

  const addExpense = useCallback(async (expense: Omit<Expense, "id">) => {
    const { data, error } = await supabase
      .from("expenses")
      .insert({
        date: expense.date,
        description: expense.description,
        category: expense.category,
        amount: expense.amount,
        type: expense.type,
        status: expense.status,
        country: expense.country || null,
        payment_source: expense.paymentSource || null,
        is_auto_generated: expense.isAutoGenerated || false,
      })
      .select()
      .single();

    if (!error && data) {
      setAllExpenses(prev => [rowToExpense(data), ...prev]);
      return { success: true };
    }

    return { success: false, error: error?.message ?? "Erro ao salvar despesa." };
  }, []);

  const updateExpense = useCallback(async (id: string, updates: Partial<Omit<Expense, "id">>) => {
    const dbUpdates: any = {};
    if (updates.description !== undefined) dbUpdates.description = updates.description;
    if (updates.amount !== undefined) dbUpdates.amount = updates.amount;
    if (updates.category !== undefined) dbUpdates.category = updates.category;
    if (updates.type !== undefined) dbUpdates.type = updates.type;
    if (updates.status !== undefined) dbUpdates.status = updates.status;
    if (updates.date !== undefined) dbUpdates.date = updates.date;
    if (updates.country !== undefined) dbUpdates.country = updates.country;
    if (updates.paymentSource !== undefined) dbUpdates.payment_source = updates.paymentSource;

    const previous = allExpenses;
    setAllExpenses(prev => prev.map(e => e.id === id ? { ...e, ...updates } : e));

    const { error } = await supabase.from("expenses").update(dbUpdates).eq("id", id);

    if (error) {
      setAllExpenses(previous);
      return { success: false, error: error.message };
    }

    return { success: true };
  }, [allExpenses]);

  const deleteExpense = useCallback(async (id: string) => {
    const previous = allExpenses;
    setAllExpenses(prev => prev.filter(e => e.id !== id));

    const { error } = await supabase.from("expenses").delete().eq("id", id);

    if (error) {
      setAllExpenses(previous);
      return { success: false, error: error.message };
    }

    return { success: true };
  }, [allExpenses]);

  const addAutoExpenses = useCallback((autoExpenses: Omit<Expense, "id">[]) => {
    setAllExpenses(prev => {
      const manual = prev.filter(e => !e.isAutoGenerated);
      const newAutos = autoExpenses.map((exp, i) => ({
        ...exp,
        id: `AUTO${String(i + 1).padStart(3, "0")}`,
      }));
      return [...newAutos, ...manual];
    });
  }, []);

  const fbAdsAccumulated = useMemo(() => {
    return allExpenses
      .filter(e => e.isAutoGenerated && e.category === "Facebook ADS" && e.status === "agendado")
      .reduce((s, e) => s + e.amount, 0);
  }, [allExpenses]);

  const registerFbAdsPayment = useCallback(async (amount: number, source: PaymentSource) => {
    const newPaid = fbAdsPaid + amount;
    const expenseData = {
      date: today,
      description: `Pagamento Facebook ADS`,
      category: "Facebook ADS",
      amount,
      type: "variavel" as const,
      status: "pago" as const,
      paymentSource: source,
    };
    const { data, error } = await supabase
      .from("expenses")
      .insert({
        date: expenseData.date, description: expenseData.description, category: expenseData.category,
        amount: expenseData.amount, type: expenseData.type, status: expenseData.status,
        payment_source: source, is_auto_generated: false,
      })
      .select()
      .single();

    if (!error && data) {
      setFbAdsPaidState(newPaid);
      persistManualValue("fbAdsPaid", newPaid);
      setAllExpenses(prev => [rowToExpense(data), ...prev]);
      return { success: true };
    }

    return { success: false, error: error?.message ?? "Erro ao registrar pagamento do Facebook ADS." };
  }, [fbAdsPaid, persistManualValue]);

  return (
    <FinanceContext.Provider value={{
      expenses, allExpenses, addExpense, updateExpense, deleteExpense, addAutoExpenses,
      registerFbAdsPayment, fbAdsAccumulated, fbAdsPaid,
      selectedDate, setSelectedDate, dateRange, setDateRange,
      countryFilter, setCountryFilter,
      manualCash, setManualCash,
      manualCashBR, setManualCashBR,
      manualCashUY, setManualCashUY,
      manualSaqueBR, setManualSaqueBR,
      manualSaqueUY, setManualSaqueUY,
    }}>
      {children}
    </FinanceContext.Provider>
  );
}

export function useFinance() {
  const ctx = useContext(FinanceContext);
  if (!ctx) throw new Error("useFinance must be used within FinanceProvider");
  return ctx;
}
