import React, { createContext, useContext, useState, useMemo, useCallback, ReactNode } from "react";
import { 
  Expense, expenses as initialExpenses, 
  expenseCategories, getTodayBR, PaymentSource
} from "@/lib/finance-data";

export type CountryFilter = "todos" | "brasil" | "uruguay";

interface FinanceContextType {
  expenses: Expense[];
  allExpenses: Expense[];
  addExpense: (expense: Omit<Expense, "id">) => void;
  updateExpense: (id: string, data: Partial<Omit<Expense, "id">>) => void;
  deleteExpense: (id: string) => void;
  addAutoExpenses: (autoExpenses: Omit<Expense, "id">[]) => void;
  registerFbAdsPayment: (amount: number, source: PaymentSource) => void;
  fbAdsAccumulated: number;
  fbAdsPaid: number;
  selectedDate: string;
  setSelectedDate: (date: string) => void;
  dateRange: { from: string; to: string };
  setDateRange: (range: { from: string; to: string }) => void;
  countryFilter: CountryFilter;
  setCountryFilter: (country: CountryFilter) => void;
  manualCash: number | null;
  setManualCash: (value: number | null) => void;
  manualSaque: number | null;
  setManualSaque: (value: number | null) => void;
}

const FinanceContext = createContext<FinanceContextType | undefined>(undefined);

const today = getTodayBR();

export function FinanceProvider({ children }: { children: ReactNode }) {
  const [allExpenses, setAllExpenses] = useState<Expense[]>(initialExpenses);
  const [selectedDate, setSelectedDate] = useState(today);
  const [dateRange, setDateRange] = useState({ from: today, to: today });
  const [countryFilter, setCountryFilter] = useState<CountryFilter>("todos");
  const [fbAdsPaid, setFbAdsPaid] = useState<number>(() => {
    const stored = localStorage.getItem("fbAdsPaid");
    return stored ? Number(stored) : 0;
  });
  const [manualCash, setManualCashState] = useState<number | null>(() => {
    const stored = localStorage.getItem("manualCash");
    return stored ? Number(stored) : null;
  });
  const [manualSaque, setManualSaqueState] = useState<number | null>(() => {
    const stored = localStorage.getItem("manualSaque");
    return stored ? Number(stored) : null;
  });

  const setManualCash = (value: number | null) => {
    setManualCashState(value);
    if (value !== null) {
      localStorage.setItem("manualCash", String(value));
    } else {
      localStorage.removeItem("manualCash");
    }
  };

  const setManualSaque = (value: number | null) => {
    setManualSaqueState(value);
    if (value !== null) {
      localStorage.setItem("manualSaque", String(value));
    } else {
      localStorage.removeItem("manualSaque");
    }
  };

  const expenses = useMemo(() => {
    if (countryFilter === "todos") return allExpenses;
    return allExpenses.filter(e => e.country === countryFilter);
  }, [allExpenses, countryFilter]);

  const addExpense = (expense: Omit<Expense, "id">) => {
    const id = `DES${String(allExpenses.length + 1).padStart(3, "0")}`;
    setAllExpenses(prev => [{ ...expense, id }, ...prev]);
  };

  const addAutoExpenses = useCallback((autoExpenses: Omit<Expense, "id">[]) => {
    setAllExpenses(prev => {
      // Remove old auto-generated, add new ones
      const manual = prev.filter(e => !e.isAutoGenerated);
      const newAutos = autoExpenses.map((exp, i) => ({
        ...exp,
        id: `AUTO${String(i + 1).padStart(3, "0")}`,
      }));
      return [...newAutos, ...manual];
    });
  }, []);

  // FB Ads accumulated = sum of all auto-generated FB Ads agendado expenses
  const fbAdsAccumulated = useMemo(() => {
    return allExpenses
      .filter(e => e.isAutoGenerated && e.category === "Facebook ADS" && e.status === "agendado")
      .reduce((s, e) => s + e.amount, 0);
  }, [allExpenses]);

  const registerFbAdsPayment = useCallback((amount: number, source: PaymentSource) => {
    const newPaid = fbAdsPaid + amount;
    setFbAdsPaid(newPaid);
    localStorage.setItem("fbAdsPaid", String(newPaid));
    // Add as a paid expense
    const id = `FBPAY${String(Date.now()).slice(-6)}`;
    setAllExpenses(prev => [{
      id,
      date: today,
      description: `Pagamento Facebook ADS`,
      category: "Facebook ADS",
      amount,
      type: "variavel" as const,
      status: "pago" as const,
      paymentSource: source,
    }, ...prev]);
  }, [fbAdsPaid]);

  return (
    <FinanceContext.Provider value={{ expenses, allExpenses, addExpense, addAutoExpenses, registerFbAdsPayment, fbAdsAccumulated, fbAdsPaid, selectedDate, setSelectedDate, dateRange, setDateRange, countryFilter, setCountryFilter, manualCash, setManualCash, manualSaque, setManualSaque }}>
      {children}
    </FinanceContext.Provider>
  );
}

export function useFinance() {
  const ctx = useContext(FinanceContext);
  if (!ctx) throw new Error("useFinance must be used within FinanceProvider");
  return ctx;
}
