import React, { createContext, useContext, useState, useMemo, useCallback, useEffect, ReactNode } from "react";
import { 
  Expense, expenses as initialExpenses, 
  expenseCategories, getTodayBR, PaymentSource
} from "@/lib/finance-data";
import { supabase } from "@/integrations/supabase/client";

export type CountryFilter = "todos" | "brasil" | "uruguay";

interface FinanceContextType {
  expenses: Expense[];
  allExpenses: Expense[];
  addExpense: (expense: Omit<Expense, "id">) => void;
  updateExpense: (id: string, data: Partial<Omit<Expense, "id">>) => void;
  deleteExpense: (id: string) => void;
  addAutoExpenses: (autoExpenses: Omit<Expense, "id">[]) => void;
  registerFbAdsPayment: (amount: number, source: PaymentSource) => void;
  fbAdsAccumulated: number;
  fbAdsPaid: number;
  selectedDate: string;
  setSelectedDate: (date: string) => void;
  dateRange: { from: string; to: string };
  setDateRange: (range: { from: string; to: string }) => void;
  countryFilter: CountryFilter;
  setCountryFilter: (country: CountryFilter) => void;
  manualCash: number | null;
  setManualCash: (value: number | null) => void;
  manualSaque: number | null;
  setManualSaque: (value: number | null) => void;
}

const FinanceContext = createContext<FinanceContextType | undefined>(undefined);

const today = getTodayBR();

// Convert DB row to Expense
function rowToExpense(row: any): Expense {
  return {
    id: row.id,
    date: row.date,
    description: row.description,
    category: row.category,
    amount: Number(row.amount),
    type: row.type as Expense["type"],
    status: row.status as Expense["status"],
    country: row.country as Expense["country"],
    paymentSource: row.payment_source as PaymentSource | undefined,
    isAutoGenerated: row.is_auto_generated,
  };
}

export function FinanceProvider({ children }: { children: ReactNode }) {
  const [allExpenses, setAllExpenses] = useState<Expense[]>(initialExpenses);
  const [dbLoaded, setDbLoaded] = useState(false);
  const [selectedDate, setSelectedDate] = useState(today);
  const [dateRange, setDateRange] = useState({ from: today, to: today });
  const [countryFilter, setCountryFilter] = useState<CountryFilter>("todos");
  const [fbAdsPaid, setFbAdsPaid] = useState<number>(() => {
    const stored = localStorage.getItem("fbAdsPaid");
    return stored ? Number(stored) : 0;
  });
  const [manualCash, setManualCashState] = useState<number | null>(() => {
    const stored = localStorage.getItem("manualCash");
    return stored ? Number(stored) : null;
  });
  const [manualSaque, setManualSaqueState] = useState<number | null>(() => {
    const stored = localStorage.getItem("manualSaque");
    return stored ? Number(stored) : null;
  });

  // Load expenses from DB on mount
  useEffect(() => {
    const loadExpenses = async () => {
      const { data, error } = await supabase
        .from("expenses")
        .select("*")
        .order("created_at", { ascending: false });
      
      if (!error && data && data.length > 0) {
        setAllExpenses(data.map(rowToExpense));
      }
      setDbLoaded(true);
    };
    loadExpenses();
  }, []);

  const setManualCash = (value: number | null) => {
    setManualCashState(value);
    if (value !== null) {
      localStorage.setItem("manualCash", String(value));
    } else {
      localStorage.removeItem("manualCash");
    }
  };

  const setManualSaque = (value: number | null) => {
    setManualSaqueState(value);
    if (value !== null) {
      localStorage.setItem("manualSaque", String(value));
    } else {
      localStorage.removeItem("manualSaque");
    }
  };

  const expenses = useMemo(() => {
    if (countryFilter === "todos") return allExpenses;
    return allExpenses.filter(e => e.country === countryFilter);
  }, [allExpenses, countryFilter]);

  const addExpense = useCallback(async (expense: Omit<Expense, "id">) => {
    const { data, error } = await supabase
      .from("expenses")
      .insert({
        date: expense.date,
        description: expense.description,
        category: expense.category,
        amount: expense.amount,
        type: expense.type,
        status: expense.status,
        country: expense.country || null,
        payment_source: expense.paymentSource || null,
        is_auto_generated: expense.isAutoGenerated || false,
      })
      .select()
      .single();

    if (!error && data) {
      setAllExpenses(prev => [rowToExpense(data), ...prev]);
    } else {
      // Fallback to local
      const id = `DES${String(Date.now()).slice(-6)}`;
      setAllExpenses(prev => [{ ...expense, id }, ...prev]);
    }
  }, []);

  const updateExpense = useCallback(async (id: string, updates: Partial<Omit<Expense, "id">>) => {
    // Update locally immediately
    setAllExpenses(prev => prev.map(e => e.id === id ? { ...e, ...updates } : e));

    // Persist to DB
    const dbUpdates: any = {};
    if (updates.description !== undefined) dbUpdates.description = updates.description;
    if (updates.amount !== undefined) dbUpdates.amount = updates.amount;
    if (updates.category !== undefined) dbUpdates.category = updates.category;
    if (updates.type !== undefined) dbUpdates.type = updates.type;
    if (updates.status !== undefined) dbUpdates.status = updates.status;
    if (updates.date !== undefined) dbUpdates.date = updates.date;
    if (updates.country !== undefined) dbUpdates.country = updates.country;
    if (updates.paymentSource !== undefined) dbUpdates.payment_source = updates.paymentSource;

    await supabase.from("expenses").update(dbUpdates).eq("id", id);
  }, []);

  const deleteExpense = useCallback(async (id: string) => {
    setAllExpenses(prev => prev.filter(e => e.id !== id));
    await supabase.from("expenses").delete().eq("id", id);
  }, []);

  const addAutoExpenses = useCallback((autoExpenses: Omit<Expense, "id">[]) => {
    setAllExpenses(prev => {
      const manual = prev.filter(e => !e.isAutoGenerated);
      const newAutos = autoExpenses.map((exp, i) => ({
        ...exp,
        id: `AUTO${String(i + 1).padStart(3, "0")}`,
      }));
      return [...newAutos, ...manual];
    });
  }, []);

  const fbAdsAccumulated = useMemo(() => {
    return allExpenses
      .filter(e => e.isAutoGenerated && e.category === "Facebook ADS" && e.status === "agendado")
      .reduce((s, e) => s + e.amount, 0);
  }, [allExpenses]);

  const registerFbAdsPayment = useCallback(async (amount: number, source: PaymentSource) => {
    const newPaid = fbAdsPaid + amount;
    setFbAdsPaid(newPaid);
    localStorage.setItem("fbAdsPaid", String(newPaid));

    const expenseData = {
      date: today,
      description: `Pagamento Facebook ADS`,
      category: "Facebook ADS",
      amount,
      type: "variavel" as const,
      status: "pago" as const,
      paymentSource: source,
    };

    // Save to DB
    const { data, error } = await supabase
      .from("expenses")
      .insert({
        date: expenseData.date,
        description: expenseData.description,
        category: expenseData.category,
        amount: expenseData.amount,
        type: expenseData.type,
        status: expenseData.status,
        payment_source: source,
        is_auto_generated: false,
      })
      .select()
      .single();

    if (!error && data) {
      setAllExpenses(prev => [rowToExpense(data), ...prev]);
    } else {
      const id = `FBPAY${String(Date.now()).slice(-6)}`;
      setAllExpenses(prev => [{ ...expenseData, id }, ...prev]);
    }
  }, [fbAdsPaid]);

  return (
    <FinanceContext.Provider value={{ expenses, allExpenses, addExpense, updateExpense, deleteExpense, addAutoExpenses, registerFbAdsPayment, fbAdsAccumulated, fbAdsPaid, selectedDate, setSelectedDate, dateRange, setDateRange, countryFilter, setCountryFilter, manualCash, setManualCash, manualSaque, setManualSaque }}>
      {children}
    </FinanceContext.Provider>
  );
}

export function useFinance() {
  const ctx = useContext(FinanceContext);
  if (!ctx) throw new Error("useFinance must be used within FinanceProvider");
  return ctx;
}
